/* tslint:disable */
/* eslint-disable */
/**
 * MareshkiFinance Service - User model
 * This is a Template YAML For mareshkifinance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { InfoHolder } from './InfoHolder';
import {
    InfoHolderFromJSON,
    InfoHolderFromJSONTyped,
    InfoHolderToJSON,
} from './InfoHolder';

/**
 * 
 * @export
 * @interface ApiSystemInfoGet200Response
 */
export interface ApiSystemInfoGet200Response {
    /**
     * 
     * @type {InfoHolder}
     * @memberof ApiSystemInfoGet200Response
     */
    data?: InfoHolder;
}

/**
 * Check if a given object implements the ApiSystemInfoGet200Response interface.
 */
export function instanceOfApiSystemInfoGet200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiSystemInfoGet200ResponseFromJSON(json: any): ApiSystemInfoGet200Response {
    return ApiSystemInfoGet200ResponseFromJSONTyped(json, false);
}

export function ApiSystemInfoGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiSystemInfoGet200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : InfoHolderFromJSON(json['data']),
    };
}

export function ApiSystemInfoGet200ResponseToJSON(value?: ApiSystemInfoGet200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': InfoHolderToJSON(value.data),
    };
}

