/* tslint:disable */
/* eslint-disable */
/**
 * MareshkiFinance Service - User model
 * This is a Template YAML For mareshkifinance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrorData
 */
export interface ErrorData {
    /**
     * 
     * @type {string}
     * @memberof ErrorData
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof ErrorData
     */
    title?: string;
    /**
     * 
     * @type {number}
     * @memberof ErrorData
     */
    status?: number;
    /**
     * 
     * @type {string}
     * @memberof ErrorData
     */
    detail?: string;
}

/**
 * Check if a given object implements the ErrorData interface.
 */
export function instanceOfErrorData(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ErrorDataFromJSON(json: any): ErrorData {
    return ErrorDataFromJSONTyped(json, false);
}

export function ErrorDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : json['type'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'detail': !exists(json, 'detail') ? undefined : json['detail'],
    };
}

export function ErrorDataToJSON(value?: ErrorData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'title': value.title,
        'status': value.status,
        'detail': value.detail,
    };
}

