/* tslint:disable */
/* eslint-disable */
/**
 * MareshkiFinance Service - User model
 * This is a Template YAML For mareshkifinance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorData } from './ErrorData';
import {
    ErrorDataFromJSON,
    ErrorDataFromJSONTyped,
    ErrorDataToJSON,
} from './ErrorData';

/**
 * 
 * @export
 * @interface TokenResponse
 */
export interface TokenResponse {
    /**
     * 
     * @type {string}
     * @memberof TokenResponse
     */
    data?: string;
    /**
     * 
     * @type {ErrorData}
     * @memberof TokenResponse
     */
    error?: ErrorData;
}

/**
 * Check if a given object implements the TokenResponse interface.
 */
export function instanceOfTokenResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TokenResponseFromJSON(json: any): TokenResponse {
    return TokenResponseFromJSONTyped(json, false);
}

export function TokenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : json['data'],
        'error': !exists(json, 'error') ? undefined : ErrorDataFromJSON(json['error']),
    };
}

export function TokenResponseToJSON(value?: TokenResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data,
        'error': ErrorDataToJSON(value.error),
    };
}

