/* tslint:disable */
/* eslint-disable */
/**
 * MareshkiFinance Service - User model
 * This is a Template YAML For mareshkifinance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadUserAvatar200Response
 */
export interface UploadUserAvatar200Response {
    /**
     * 
     * @type {string}
     * @memberof UploadUserAvatar200Response
     */
    avatarUrl?: string;
}

/**
 * Check if a given object implements the UploadUserAvatar200Response interface.
 */
export function instanceOfUploadUserAvatar200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UploadUserAvatar200ResponseFromJSON(json: any): UploadUserAvatar200Response {
    return UploadUserAvatar200ResponseFromJSONTyped(json, false);
}

export function UploadUserAvatar200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadUserAvatar200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'avatarUrl': !exists(json, 'avatar_url') ? undefined : json['avatar_url'],
    };
}

export function UploadUserAvatar200ResponseToJSON(value?: UploadUserAvatar200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'avatar_url': value.avatarUrl,
    };
}

