/* tslint:disable */
/* eslint-disable */
/**
 * MareshkiFinance Service - User model
 * This is a Template YAML For mareshkifinance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserProfileUpdateAddress } from './UserProfileUpdateAddress';
import {
    UserProfileUpdateAddressFromJSON,
    UserProfileUpdateAddressFromJSONTyped,
    UserProfileUpdateAddressToJSON,
} from './UserProfileUpdateAddress';
import type { UserProfileUpdateName } from './UserProfileUpdateName';
import {
    UserProfileUpdateNameFromJSON,
    UserProfileUpdateNameFromJSONTyped,
    UserProfileUpdateNameToJSON,
} from './UserProfileUpdateName';

/**
 * 
 * @export
 * @interface UserProfileUpdate
 */
export interface UserProfileUpdate {
    /**
     * 
     * @type {UserProfileUpdateName}
     * @memberof UserProfileUpdate
     */
    name: UserProfileUpdateName;
    /**
     * 
     * @type {UserProfileUpdateAddress}
     * @memberof UserProfileUpdate
     */
    address: UserProfileUpdateAddress;
}

/**
 * Check if a given object implements the UserProfileUpdate interface.
 */
export function instanceOfUserProfileUpdate(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "address" in value;

    return isInstance;
}

export function UserProfileUpdateFromJSON(json: any): UserProfileUpdate {
    return UserProfileUpdateFromJSONTyped(json, false);
}

export function UserProfileUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfileUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': UserProfileUpdateNameFromJSON(json['name']),
        'address': UserProfileUpdateAddressFromJSON(json['address']),
    };
}

export function UserProfileUpdateToJSON(value?: UserProfileUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': UserProfileUpdateNameToJSON(value.name),
        'address': UserProfileUpdateAddressToJSON(value.address),
    };
}

