/* tslint:disable */
/* eslint-disable */
/**
 * MareshkiFinance Service - User model
 * This is a Template YAML For mareshkifinance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserProfileUpdateName
 */
export interface UserProfileUpdateName {
    /**
     * 
     * @type {string}
     * @memberof UserProfileUpdateName
     */
    first?: string;
}

/**
 * Check if a given object implements the UserProfileUpdateName interface.
 */
export function instanceOfUserProfileUpdateName(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserProfileUpdateNameFromJSON(json: any): UserProfileUpdateName {
    return UserProfileUpdateNameFromJSONTyped(json, false);
}

export function UserProfileUpdateNameFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfileUpdateName {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'first': !exists(json, 'first') ? undefined : json['first'],
    };
}

export function UserProfileUpdateNameToJSON(value?: UserProfileUpdateName | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'first': value.first,
    };
}

