/* tslint:disable */
/* eslint-disable */
/**
 * MareshkiFinance Service - User model
 * This is a Template YAML For mareshkifinance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserProfileResponse
 */
export interface UserProfileResponse {
    /**
     * 
     * @type {number}
     * @memberof UserProfileResponse
     */
    userId?: number;
    /**
     * 
     * @type {string}
     * @memberof UserProfileResponse
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileResponse
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileResponse
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileResponse
     */
    profilePictureUrl?: string | null;
}

/**
 * Check if a given object implements the UserProfileResponse interface.
 */
export function instanceOfUserProfileResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserProfileResponseFromJSON(json: any): UserProfileResponse {
    return UserProfileResponseFromJSONTyped(json, false);
}

export function UserProfileResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfileResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'firstName': !exists(json, 'firstName') ? undefined : json['firstName'],
        'username': !exists(json, 'username') ? undefined : json['username'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'profilePictureUrl': !exists(json, 'profile_picture_url') ? undefined : json['profile_picture_url'],
    };
}

export function UserProfileResponseToJSON(value?: UserProfileResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
        'firstName': value.firstName,
        'username': value.username,
        'email': value.email,
        'profile_picture_url': value.profilePictureUrl,
    };
}

