/* tslint:disable */
/* eslint-disable */
/**
 * MareshkiFinance Service - User model
 * This is a Template YAML For mareshkifinance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserProfileUpdateAddress
 */
export interface UserProfileUpdateAddress {
    /**
     * 
     * @type {string}
     * @memberof UserProfileUpdateAddress
     */
    country?: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileUpdateAddress
     */
    city?: string;
}

/**
 * Check if a given object implements the UserProfileUpdateAddress interface.
 */
export function instanceOfUserProfileUpdateAddress(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserProfileUpdateAddressFromJSON(json: any): UserProfileUpdateAddress {
    return UserProfileUpdateAddressFromJSONTyped(json, false);
}

export function UserProfileUpdateAddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfileUpdateAddress {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'country': !exists(json, 'country') ? undefined : json['country'],
        'city': !exists(json, 'city') ? undefined : json['city'],
    };
}

export function UserProfileUpdateAddressToJSON(value?: UserProfileUpdateAddress | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'country': value.country,
        'city': value.city,
    };
}

