/* tslint:disable */
/* eslint-disable */
/**
 * MareshkiFinance Service - User model
 * This is a Template YAML For mareshkifinance
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * This is a UserRegistration object
 * @export
 * @interface UserRegistration
 */
export interface UserRegistration {
    /**
     * 
     * @type {string}
     * @memberof UserRegistration
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserRegistration
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof UserRegistration
     */
    email?: string;
}

/**
 * Check if a given object implements the UserRegistration interface.
 */
export function instanceOfUserRegistration(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserRegistrationFromJSON(json: any): UserRegistration {
    return UserRegistrationFromJSONTyped(json, false);
}

export function UserRegistrationFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRegistration {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'firstName': !exists(json, 'firstName') ? undefined : json['firstName'],
        'password': !exists(json, 'password') ? undefined : json['password'],
        'email': !exists(json, 'email') ? undefined : json['email'],
    };
}

export function UserRegistrationToJSON(value?: UserRegistration | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'firstName': value.firstName,
        'password': value.password,
        'email': value.email,
    };
}

