// This file is auto-generated by @hey-api/openapi-ts

export const $InfoHolder = {
    description: 'This is an object holding the version information',
    type: 'object',
    properties: {
        appBuildversion: {
            type: 'string'
        },
        appBuildTime: {
            type: 'string'
        }
    }
} as const;

export const $ErrorResponse = {
    description: 'This is the response object in case of errors, compliant with RFC7807',
    type: 'object',
    properties: {
        error: {
            '$ref': '#/components/schemas/ErrorData'
        }
    }
} as const;

export const $ErrorData = {
    type: 'object',
    properties: {
        type: {
            type: 'string'
        },
        title: {
            type: 'string'
        },
        status: {
            type: 'integer'
        },
        detail: {
            type: 'string'
        }
    }
} as const;

export const $TokenResponse = {
    type: 'object',
    properties: {
        data: {
            type: 'string'
        },
        error: {
            '$ref': '#/components/schemas/ErrorData'
        }
    }
} as const;

export const $UserLogin = {
    description: 'This is a UserLogin object',
    type: 'object',
    properties: {
        email: {
            type: 'string',
            format: 'email',
            pattern: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
        },
        password: {
            type: 'string',
            minLength: 8,
            maxLength: 50
        }
    }
} as const;

export const $UserRegistration = {
    description: 'This is a UserRegistration object',
    type: 'object',
    properties: {
        firstName: {
            type: 'string',
            pattern: '^[a-zA-Z]{3,15}$'
        },
        password: {
            type: 'string',
            minLength: 8,
            maxLength: 50
        },
        email: {
            type: 'string',
            format: 'email',
            pattern: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
        }
    }
} as const;

export const $UserProfileResponse = {
    type: 'object',
    properties: {
        userId: {
            type: 'integer'
        },
        firstName: {
            type: 'string',
            pattern: '^[a-zA-Z]{3,15}$'
        },
        username: {
            type: 'string'
        },
        email: {
            type: 'string'
        },
        profile_picture_url: {
            type: 'string',
            nullable: true
        }
    }
} as const;

export const $UserProfileUpdate = {
    type: 'object',
    properties: {
        name: {
            type: 'object',
            properties: {
                first: {
                    type: 'string'
                }
            }
        },
        address: {
            type: 'object',
            properties: {
                country: {
                    type: 'string'
                },
                city: {
                    type: 'string'
                }
            }
        }
    },
    required: ['name', 'address']
} as const;